# Generated by Django 2.2 on 2020-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=50)),
                ('outstandingbalance', models.FloatField()),
            ],
        ),
    ]
